# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
    provider: pypi
    distributions: sdist bdist_wheel
    user: wmshort
    password:
      secure: bjss6zo2qyj+SasgM4MR6UDicKDcLxyc+hakeVLZUA4aiZHl0cBIXg8R/Tq5Kyi0z2lzVDd1j6YTMwzxO+lwWORtJjV7Y06ZXqQqBqR6E3wKstEo7ZjCbX
      zOwUcwLAgVugDJqfsTRiHeF/l0IEz7TthPUq97APFeZUYknGhKCViE2OF+mWl3nD741+0EZUU5ouxEn+tAc50rzAngFMH4AduaZtLjVRALxAndJ2aTsLftduLOz8ZN008E
      8RaBewaF5e9NpvGPDKhIn+NQf0S+4mEsvnb/ZnntU4MbBgiY2Pu5osmG7cNrXkhAyU0tIYnA34AXNJhCsTkUVV8qBivIfwXexVSafznCVQcRkPYkrLfrQHF3ffEh8TYdGG
      we6Cowf1x0KPwlzM1XsM8gaz3Fspm1qcrAa/w0G7dbiZEpWX3dt2Crrak7l8UROlAoa5boB1xwk90evzFSpvhcHUjh5wEB+o10kHQkxU6vGrMKYwCn4V9dFGpcJ2v/91na
      Vg2Di/wevlK6+d54tOOXe1Co8HpCs5Q4O0Z5mPLP6QpcMxvncVemx31Yf713T8Q4S9C4+H6hQNEJ+kbljuskICIna/eYcGExk/GuTt/7cFDQjwqV4YL6mrXNhJE52PNRXM
      P5tataVgIlMdJKR85EQZSVpRXPMIs015qeG9ObEKqxQQU=
    on:
        tags: true
        repo: wmshort/multiwordnet
        python: 3.6
