# Host: 	    Database: 	    Date: 
# ---------------------------------------------------------
#

DROP TABLE IF EXISTS semfield_hierarchy;
CREATE TABLE semfield_hierarchy ( code int(11) DEFAULT '0' NOT NULL, english varchar(30), normal text, hypers varchar(50), hypons text, PRIMARY KEY (code));

INSERT INTO semfield_hierarchy VALUES (125,'Animal_Husbandry','Applied_Science','Agriculture','Veterinary');
INSERT INTO semfield_hierarchy VALUES (109,'Buildings','Applied_Science','Architecture','');
INSERT INTO semfield_hierarchy VALUES (215,'Diplomacy','Social_Science','Politics','');
INSERT INTO semfield_hierarchy VALUES (7,'Metrology','','Factotum','');
INSERT INTO semfield_hierarchy VALUES (81,'Mountaineering','Free_Time','Sport','');
INSERT INTO semfield_hierarchy VALUES (192,'Artisanship','Artisanship','Social_Science','');
INSERT INTO semfield_hierarchy VALUES (188,'Anthropology','Anthropology','Social_Science','Ethnology');
INSERT INTO semfield_hierarchy VALUES (165,'Geography','Pure_Science','Earth','Topography');
INSERT INTO semfield_hierarchy VALUES (118,'Dentistry','Applied_Science','Medicine','');
INSERT INTO semfield_hierarchy VALUES (37,'Grammar','Humanities','Linguistics','');
INSERT INTO semfield_hierarchy VALUES (217,'Sexuality','Sexuality','Social_Science','');
INSERT INTO semfield_hierarchy VALUES (202,'Book_Keeping','Social_Science','Enterprise','');
INSERT INTO semfield_hierarchy VALUES (106,'Gastronomy','Applied_Science','Food','');
INSERT INTO semfield_hierarchy VALUES (203,'Finance','Social_Science','Economy','Banking Money Exchange');
INSERT INTO semfield_hierarchy VALUES (26,'Photography','Humanities','Art','');
INSERT INTO semfield_hierarchy VALUES (61,'Chess','Free_Time','Play','');
INSERT INTO semfield_hierarchy VALUES (63,'Card','Free_Time','Play','');
INSERT INTO semfield_hierarchy VALUES (24,'Painting','Humanities','Art','');
INSERT INTO semfield_hierarchy VALUES (21,'Dance','Humanities','Art','');
INSERT INTO semfield_hierarchy VALUES (153,'Oceanography','Pure_Science','Earth','');
INSERT INTO semfield_hierarchy VALUES (208,'Industry','Industry','Social_Science','');
INSERT INTO semfield_hierarchy VALUES (206,'Exchange','Economy','Finance','');
INSERT INTO semfield_hierarchy VALUES (159,'Physics','Physics','Pure_Science','Acoustics Atomic_Physic Electricity Gas Optics');
INSERT INTO semfield_hierarchy VALUES (79,'Skiing','Free_Time','Sport','');
INSERT INTO semfield_hierarchy VALUES (89,'Boxing','Free_Time','Sport','');
INSERT INTO semfield_hierarchy VALUES (114,'Electrotechnology','Applied_Science','Engineering','');
INSERT INTO semfield_hierarchy VALUES (111,'Engineering','Engineering','Applied_Science','Mechanics Astronautics Electrotechnology Hydraulics');
INSERT INTO semfield_hierarchy VALUES (83,'Swimming','Free_Time','Sport','');
INSERT INTO semfield_hierarchy VALUES (157,'Geometry','Pure_Science','Mathematics','');
INSERT INTO semfield_hierarchy VALUES (29,'Drawing','Humanities','Art','');
INSERT INTO semfield_hierarchy VALUES (211,'Pedagogy','Pedagogy','Social_Science','School University');
INSERT INTO semfield_hierarchy VALUES (223,'Tourism','Tourism','Social_Science','');
INSERT INTO semfield_hierarchy VALUES (95,'Racing','Free_Time','Sport','');
INSERT INTO semfield_hierarchy VALUES (74,'Table_Tennis','Free_Time','Sport','');
INSERT INTO semfield_hierarchy VALUES (66,'Badminton','Free_Time','Sport','');
INSERT INTO semfield_hierarchy VALUES (191,'Folklore','Social_Science','Ethnology','');
INSERT INTO semfield_hierarchy VALUES (108,'Town_Planning','Applied_Science','Architecture','');
INSERT INTO semfield_hierarchy VALUES (73,'Soccer','Free_Time','Sport','');
INSERT INTO semfield_hierarchy VALUES (87,'Athletics','Free_Time','Sport','');
INSERT INTO semfield_hierarchy VALUES (25,'Music','Humanities','Art','');
INSERT INTO semfield_hierarchy VALUES (213,'University','Social_Science','Pedagogy','');
INSERT INTO semfield_hierarchy VALUES (209,'Law','Law','Social_Science','');
INSERT INTO semfield_hierarchy VALUES (49,'Astrology','Humanities','Paranormal','');
INSERT INTO semfield_hierarchy VALUES (69,'Cricket','Free_Time','Sport','');
INSERT INTO semfield_hierarchy VALUES (187,'Administration','Administration','Social_Science','');
INSERT INTO semfield_hierarchy VALUES (205,'Money','Economy','Finance','');
INSERT INTO semfield_hierarchy VALUES (194,'Body_Care','Social_Science','Health','');
INSERT INTO semfield_hierarchy VALUES (134,'Environment','Environment','Pure_Science','');
INSERT INTO semfield_hierarchy VALUES (51,'Mythology','Humanities','Religion','');
INSERT INTO semfield_hierarchy VALUES (200,'Tax','Social_Science','Economy','');
INSERT INTO semfield_hierarchy VALUES (146,'Entomology','Pure_Science','Animals','');
INSERT INTO semfield_hierarchy VALUES (160,'Acoustics','Pure_Science','Physics','');
INSERT INTO semfield_hierarchy VALUES (156,'Mathematics','Mathematics','Pure_Science','Geometry Statistics');
INSERT INTO semfield_hierarchy VALUES (75,'Tennis','Free_Time','Sport','');
INSERT INTO semfield_hierarchy VALUES (119,'Pharmacy','Applied_Science','Medicine','');
INSERT INTO semfield_hierarchy VALUES (5,'Person','','Factotum','');
INSERT INTO semfield_hierarchy VALUES (218,'Sociology','Sociology','Social_Science','');
INSERT INTO semfield_hierarchy VALUES (115,'Hydraulics','Applied_Science','Engineering','');
INSERT INTO semfield_hierarchy VALUES (225,'Aviation','Social_Science','Transport','');
INSERT INTO semfield_hierarchy VALUES (117,'Medicine','Medicine','Applied_Science','Dentistry Pharmacy Psychiatry Radiology Surgery');
INSERT INTO semfield_hierarchy VALUES (1,'Factotum','Factotum','','Number Color Time_Period Person Quality Metrology Psychological_Features');
INSERT INTO semfield_hierarchy VALUES (80,'Hockey','Free_Time','Sport','');
INSERT INTO semfield_hierarchy VALUES (145,'Animals','Animals','Pure_Science','Entomology');
INSERT INTO semfield_hierarchy VALUES (212,'School','Social_Science','Pedagogy','');
INSERT INTO semfield_hierarchy VALUES (128,'Computer_Science','Computer_Science','Applied_Science','');
INSERT INTO semfield_hierarchy VALUES (105,'Food','Food','Applied_Science','Gastronomy');
INSERT INTO semfield_hierarchy VALUES (92,'Fishing','Free_Time','Sport','');
INSERT INTO semfield_hierarchy VALUES (71,'Golf','Free_Time','Sport','');
INSERT INTO semfield_hierarchy VALUES (210,'Military','Military','Social_Science','');
INSERT INTO semfield_hierarchy VALUES (195,'Commerce','Commerce','Social_Science','');
INSERT INTO semfield_hierarchy VALUES (35,'Archaeology','Humanities','History','');
INSERT INTO semfield_hierarchy VALUES (120,'Psychiatry','Applied_Science','Medicine','');
INSERT INTO semfield_hierarchy VALUES (122,'Surgery','Applied_Science','Medicine','');
INSERT INTO semfield_hierarchy VALUES (4,'Time_Period','','Factotum','');
INSERT INTO semfield_hierarchy VALUES (144,'Genetics','Pure_Science','Biology','');
INSERT INTO semfield_hierarchy VALUES (226,'Vehicles','Social_Science','Transport','');
INSERT INTO semfield_hierarchy VALUES (42,'Jewellery','Humanities','Plastic_Arts','');
INSERT INTO semfield_hierarchy VALUES (67,'Baseball','Free_Time','Sport','');
INSERT INTO semfield_hierarchy VALUES (76,'Volleyball','Free_Time','Sport','');
INSERT INTO semfield_hierarchy VALUES (31,'Graphic_Arts','Humanities','Art','Philately');
INSERT INTO semfield_hierarchy VALUES (149,'Chemistry','Chemistry','Pure_Science','');
INSERT INTO semfield_hierarchy VALUES (96,'Applied_Science','','','Agriculture Food Home Architecture Computer_Science Engineering Telecommunication Medicine');
INSERT INTO semfield_hierarchy VALUES (64,'Radio_TV','Radio_TV','Free_Time','');
INSERT INTO semfield_hierarchy VALUES (50,'Religion','Religion','Humanities','Mythology Roman_Catholic Theology');
INSERT INTO semfield_hierarchy VALUES (90,'Fencing','Free_Time','Sport','');
INSERT INTO semfield_hierarchy VALUES (168,'Electronics','Pure_Science','Electricity','');
INSERT INTO semfield_hierarchy VALUES (34,'Heraldry','Humanities','History','');
INSERT INTO semfield_hierarchy VALUES (154,'Paleontology','Pure_Science','Earth','');
INSERT INTO semfield_hierarchy VALUES (93,'Hunting','Free_Time','Sport','');
INSERT INTO semfield_hierarchy VALUES (219,'Telecommunication','Telecommunication','Applied_Science','Post Telegraphy Telephony');
INSERT INTO semfield_hierarchy VALUES (113,'Astronautics','Applied_Science','Engineering','');
INSERT INTO semfield_hierarchy VALUES (167,'Electricity','Pure_Science','Physics','Electronics');
INSERT INTO semfield_hierarchy VALUES (199,'Insurance','Social_Science','Economy','');
INSERT INTO semfield_hierarchy VALUES (207,'Fashion','Fashion','Social_Science','');
INSERT INTO semfield_hierarchy VALUES (6,'Quality','','Factotum','');
INSERT INTO semfield_hierarchy VALUES (84,'Sub','Free_Time','Sport','');
INSERT INTO semfield_hierarchy VALUES (53,'Theology','Humanities','Religion','');
INSERT INTO semfield_hierarchy VALUES (116,'Mechanics','Applied_Science','Engineering','');
INSERT INTO semfield_hierarchy VALUES (224,'Transport','Transport','Social_Science','Aviation Vehicles Nautical Railway');
INSERT INTO semfield_hierarchy VALUES (43,'Numismatics','Humanities','Plastic_Arts','');
INSERT INTO semfield_hierarchy VALUES (40,'Philosophy','Philosophy','Humanities','');
INSERT INTO semfield_hierarchy VALUES (227,'Nautical','Social_Science','Transport','');
INSERT INTO semfield_hierarchy VALUES (33,'History','History','Humanities','Heraldry Archaeology');
INSERT INTO semfield_hierarchy VALUES (141,'Biochemistry','Pure_Science','Biology','');
INSERT INTO semfield_hierarchy VALUES (70,'Football','Free_Time','Sport','');
INSERT INTO semfield_hierarchy VALUES (221,'Telegraphy','Applied_Science','Telecommunication','');
INSERT INTO semfield_hierarchy VALUES (140,'Biology','Biology','Pure_Science','Biochemistry Anatomy Physiology Genetics');
INSERT INTO semfield_hierarchy VALUES (39,'Philology','Humanities','Literature','');
INSERT INTO semfield_hierarchy VALUES (143,'Physiology','Pure_Science','Biology','');
INSERT INTO semfield_hierarchy VALUES (65,'Sport','Sport','Free_Time','Badminton Baseball Basketball Cricket Football Golf Rugby Soccer Table_Tennis Tennis Volleyball Cycling Skating Skiing Hockey Mountaineering Rowing Swimming Sub Diving Racing Athletics Wrestling Boxing Fencing Archery Fishing Hunting Bowling');
INSERT INTO semfield_hierarchy VALUES (190,'Ethnology','Social_Science','Anthropology','Folklore');
INSERT INTO semfield_hierarchy VALUES (196,'Economy','Economy','Social_Science','Enterprise Finance Insurance Tax');
INSERT INTO semfield_hierarchy VALUES (88,'Wrestling','Free_Time','Sport','');
INSERT INTO semfield_hierarchy VALUES (201,'Enterprise','Social_Science','Economy','Book_Keeping');
INSERT INTO semfield_hierarchy VALUES (38,'Literature','Literature','Humanities','Philology');
INSERT INTO semfield_hierarchy VALUES (85,'Diving','Free_Time','Sport','');
INSERT INTO semfield_hierarchy VALUES (107,'Architecture','Architecture','Applied_Science','Town_Planning Buildings Furniture');
INSERT INTO semfield_hierarchy VALUES (214,'Politics','Politics','Social_Science','Diplomacy');
INSERT INTO semfield_hierarchy VALUES (19,'Art','Art','Humanities','Cinema Dance Drawing Graphic_Arts Painting Music Photography Plastic_Arts Theatre');
INSERT INTO semfield_hierarchy VALUES (44,'Sculpture','Humanities','Plastic_Arts','');
INSERT INTO semfield_hierarchy VALUES (2,'Number','','Factotum','');
INSERT INTO semfield_hierarchy VALUES (77,'Cycling','Free_Time','Sport','');
INSERT INTO semfield_hierarchy VALUES (126,'Veterinary','Agriculture','Animal_Husbandry','');
INSERT INTO semfield_hierarchy VALUES (158,'Statistics','Pure_Science','Mathematics','');
INSERT INTO semfield_hierarchy VALUES (32,'Philately','Art','Graphic_Arts','');
INSERT INTO semfield_hierarchy VALUES (161,'Atomic_Physic','Pure_Science','Physics','');
INSERT INTO semfield_hierarchy VALUES (166,'Topography','Earth','Geography','');
INSERT INTO semfield_hierarchy VALUES (8,'Psychological_Features','','Factotum','');
INSERT INTO semfield_hierarchy VALUES (94,'Bowling','Free_Time','Sport','');
INSERT INTO semfield_hierarchy VALUES (68,'Basketball','Free_Time','Sport','');
INSERT INTO semfield_hierarchy VALUES (129,'Pure_Science','','','Astronomy Biology Animals Plants Environment Chemistry Earth Mathematics Physics');
INSERT INTO semfield_hierarchy VALUES (193,'Health','Health','Social_Science','Body_Care');
INSERT INTO semfield_hierarchy VALUES (58,'Play','Play','Free_Time','Betting Card Chess');
INSERT INTO semfield_hierarchy VALUES (222,'Telephony','Applied_Science','Telecommunication','');
INSERT INTO semfield_hierarchy VALUES (142,'Anatomy','Pure_Science','Biology','');
INSERT INTO semfield_hierarchy VALUES (46,'Psychoanalysis','Humanities','Psychology','');
INSERT INTO semfield_hierarchy VALUES (52,'Roman_Catholic','Humanities','Religion','');
INSERT INTO semfield_hierarchy VALUES (220,'Post','Applied_Science','Telecommunication','');
INSERT INTO semfield_hierarchy VALUES (121,'Radiology','Applied_Science','Medicine','');
INSERT INTO semfield_hierarchy VALUES (139,'Astronomy','Astronomy','Pure_Science','');
INSERT INTO semfield_hierarchy VALUES (20,'Cinema','Humanities','Art','');
INSERT INTO semfield_hierarchy VALUES (36,'Linguistics','Linguistics','Humanities','Grammar');
INSERT INTO semfield_hierarchy VALUES (91,'Archery','Free_Time','Sport','');
INSERT INTO semfield_hierarchy VALUES (147,'Plants','Plants','Pure_Science','');
INSERT INTO semfield_hierarchy VALUES (48,'Occultism','Humanities','Paranormal','');
INSERT INTO semfield_hierarchy VALUES (169,'Social_Science','','','Administration Anthropology Artisanship Health Commerce Economy Fashion Industry Law Military Pedagogy Politics Publishing Sexuality Sociology Tourism Transport');
INSERT INTO semfield_hierarchy VALUES (150,'Earth','Earth','Pure_Science','Geology Meteorology Oceanography Paleontology Geography');
INSERT INTO semfield_hierarchy VALUES (82,'Rowing','Free_Time','Sport','');
INSERT INTO semfield_hierarchy VALUES (151,'Geology','Pure_Science','Earth','');
INSERT INTO semfield_hierarchy VALUES (9,'Humanities','','','History Linguistics Literature Philosophy Psychology Art Religion Paranormal');
INSERT INTO semfield_hierarchy VALUES (228,'Railway','Social_Science','Transport','');
INSERT INTO semfield_hierarchy VALUES (110,'Furniture','Applied_Science','Architecture','');
INSERT INTO semfield_hierarchy VALUES (123,'Agriculture','Agriculture','Applied_Science','Animal_Husbandry');
INSERT INTO semfield_hierarchy VALUES (72,'Rugby','Free_Time','Sport','');
INSERT INTO semfield_hierarchy VALUES (41,'Plastic_Arts','Humanities','Art','Jewellery Numismatics Sculpture');
INSERT INTO semfield_hierarchy VALUES (127,'Home','Home','Applied_Science','');
INSERT INTO semfield_hierarchy VALUES (62,'Betting','Free_Time','Play','');
INSERT INTO semfield_hierarchy VALUES (47,'Paranormal','Paranormal','Humanities','Occultism Astrology');
INSERT INTO semfield_hierarchy VALUES (28,'Theatre','Humanities','Art','');
INSERT INTO semfield_hierarchy VALUES (54,'Free_Time','','','Play Radio_TV Sport');
INSERT INTO semfield_hierarchy VALUES (78,'Skating','Free_Time','Sport','');
INSERT INTO semfield_hierarchy VALUES (45,'Psychology','Psychology','Humanities','Psychoanalysis');
INSERT INTO semfield_hierarchy VALUES (164,'Optics','Pure_Science','Physics','');
INSERT INTO semfield_hierarchy VALUES (216,'Publishing','Publishing','Social_Science','');
INSERT INTO semfield_hierarchy VALUES (152,'Meteorology','Pure_Science','Earth','');
INSERT INTO semfield_hierarchy VALUES (204,'Banking','Economy','Finance','');
INSERT INTO semfield_hierarchy VALUES (163,'Gas','Pure_Science','Physics','');
INSERT INTO semfield_hierarchy VALUES (3,'Color','','Factotum','');
